---
- hosts: all
  tasks:
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Install basic list of packages
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
      state: present
      update_cache: yes

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker packages
    apt:
      name: ['docker-ce','docker-ce-cli','containerd.io']
      state: present

  - name: Install Docker-compose 
    become: yes
    get_url:
     url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
     dest: /usr/local/bin/docker-compose
     mode: +x
  
  - name: Install Nginx
    apt: 
      name=nginx
      state=present 

  - name: Start nginx service
    service:
     name: nginx
     state: started
  
  - name: Copy my conf
    copy:
     src: apispa.conf
     dest: /etc/nginx/sites-available/apispa.conf
    notify:
     - restart nginx

  - name: Link my conf
    file:
     src: /etc/nginx/sites-available/apispa.conf
     dest: /etc/nginx/sites-enabled/apispa.conf
     state: link
   notify:
    - restart nginx

  - name: Add user
    user:
     name: operator
     state: present
  